---
- name: Copier docker-compose.yml vers /opt/myapp
  ansible.builtin.copy:
    src: docker-compose.yml # Prend le fichier principal docker-compose (qui définit tous les conteneurs)
    dest: "{{ app_dir }}/docker-compose.yml" # L'envoie sur le serveur
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Déployer le fichier .env avec les identifiants Neon PostgreSQL
  ansible.builtin.copy:
    dest: "{{ app_dir }}/.env" # Crée le fichier de variables d'environnement caché (.env) sur le serveur
    owner: ubuntu
    group: ubuntu
    mode: '0600' # Protégé : seul l'utilisateur ubuntu peut lire ces mots de passe !
    content: |
      DOCKERHUB_USERNAME=abdoulayely777
      APP_TAG=latest
      SPRING_DATASOURCE_URL=jdbc:postgresql://ep-twilight-frost-b5wgpznz-pooler.c-7.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME=neondb_owner
      SPRING_DATASOURCE_PASSWORD=npg_4HBwLetzRDh5
      GRAFANA_ADMIN_PASSWORD=AdminDevOps2026!

- name: Télécharger et démarrer les services d'infrastructure (Traefik, Prometheus, Grafana, Node Exporter, cAdvisor, SonarQube)
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}" # Indique où se trouve le fichier docker-compose.yml
    services: # Tous les conteneurs de l'infrastructure, du backend et du frontend
      - traefik
      - prometheus
      - grafana
      - node-exporter
      - cadvisor
      - sonarqube
      - application
      - front
    state: present # Demande à Docker Compose de télécharger les images et de lancer ces conteneurs
