---
- name: Ensure SonarQube kernel parameters are loaded
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes

- name: Ensure SonarQube file limit is loaded
  ansible.posix.sysctl:
    name: fs.file-max
    value: "65536"
    state: present
    reload: yes
